dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
  - master
  - dev
  - test

install:
  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "hackydojo"
    token: ${SONAR_TOKEN}
script:
  - sh run_tests.sh
  - sonar-scanner



